export const SET_SONGLIST = 'SET_SONGLIST';

export const SET_SPOTIFY_API = 'SET_SPOTIFY_API';
export const SET_SPOTIFY_ID = 'SET_SPOTIFY_ID';
export const SET_SPOTIFY_SEARCH_RESULTS = 'SET_SPOTIFY_SEARCH_RESULTS';
export const SET_SELECTED_PLAYLIST = 'SET_SELECTED_PLAYLIST';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

