export const SET_SONGLIST = 'SET_SONGLIST';
export const SET_SPOTIFY_API = 'SET_SPOTIFY_API';
export const SET_SPOTIFY_ID = 'SET_SPOTIFY_ID';
export const SET_SELECTED_PLAYLIST = 'SET_SELECTED_PLAYLIST';
export const SET_COMPLETED_SEARCH = 'SET_COMPLETED_SEARCH'